- repeat: 2
  data:
    name: Chengdu
    meta:
      - type: trip
  
  models:
    - name: transformer_encoder
      config:
        d_model: 64
        road_col: 1
        output_size: 64
        num_layers: 2
  
  pretrain:
    load: true
    loss:
      name: mlm
      config:
        road_col: 1
        embed_dim: 64
        hidden_size: 128
    trainer:
      name: generative
      config:
        num_epoch: 20
        batch_size: 128
        lr: 1.0e-3
  
  downstream:
    - task: tte
      select_models: [0]
      eval_set: 2
      config:
        finetune: true
        num_epoch: 100
        batch_size: 128
        save_prediction: false
        lr: 1.0e-3
        es_epoch: 10